encryptionsalt: v1:04f8lKSrnPg=:v1:fmfmI/kH6HmEtCID:5Jgwk4/ywhs0PvsATnXfdvskfjwiBA==
config:
  aws:region: us-east-1
  hermes:domains:
    - gokeinvestmentcorp.com
  hermes:subnetIds:
    - subnet-ed6c2fa0
    - subnet-7312d542
    - subnet-b179c5ee
    - subnet-2747f906
    - subnet-396d1837
    - subnet-6208b804
  hermes:vpcId: vpc-ea975897
